# .github/workflows/ci-dev.yml
name: CI (dev)

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # nodig voor pre-commit hooks die refs inspecteren

  setup-python:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

  install-deps:
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install pytest hassfest pre-commit

  pre-commit:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

  run-tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    env:
      PYTHONPATH: .
    steps:
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
      - name: Debug on failure
        if: failure()
        uses: mxschmitt/action-tmate@v3
        
  hassfest:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
