name: Pre-commit Auto-fix

on:
  push:
    branches:
      - dev
  workflow_dispatch: {}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'


      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Auto-fix with pre-commit/action
        uses: pre-commit/action@v4
        with:
          extra_args: --all-files
          # Make fixes and commit:
          auto_add: true
          commit: true
          create_pull_request: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

