name: Pre-commit Auto-fix

on:
  push:
    branches:
      - dev
  workflow_dispatch: {}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit autofix
        run: |
          pre-commit run --show-diff-on-failure --color always
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "chore: apply pre-commit fixes"

      - name: Create Pull Request for Pre-commit Fixes
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Auto: pre-commit fixes"
          commit-message: "chore: apply pre-commit fixes"
          branch: pre-commit-fixes
          base: dev
          draft: false
