name: Create release zip

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r simple_pid_controller.zip custom_components/simple_pid_controller

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: simple_pid_controller.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
